# preserve nvim color scheme in tmux
set-option -sa terminal-overrides ",xterm*:Tc"
set -g default-terminal "tmux-256color"

set -g status-right ' #{whoami}@#h '

set -g history-limit 50000

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set -g renumber-windows on

set -g focus-events on

set -g mouse on

set -g mode-keys vi
bind Space copy-mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-q send-keys -X rectangle-toggle # C-v is intercepted on WSL
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Use Shift-Arrow to switch windows
bind -n S-Left previous-window
bind -n S-Right next-window

bind c new-window -c '#{pane_current_path}'
bind s split-window -v -c '#{pane_current_path}'
bind v split-window -h -c '#{pane_current_path}'

setw -g window-status-format '#[fg=black]#{?window_zoomed_flag,(, }#I#{?window_zoomed_flag,), }#W@#(basename "#{pane_current_path}") #[default]'
setw -g window-status-current-format '#[fg=colour253,bg=black]#{?window_zoomed_flag,(, }#I#{?window_zoomed_flag,), }#W@#(basename "#{pane_current_path}") #[default]'
